# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Namari
                                 A QGIS plugin
 This plugin allows you to detect anomalous features in spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-19
        copyright            : (C) 2021 by Rein van 't Veer
        email                : rein@vantveer.me
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Namari class from file Namari.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .namari import Namari
    return Namari(iface)
