# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Namari
                                 A QGIS plugin
 This plugin allows you to detect anomalous features in spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-19
        copyright            : (C) 2021 by Rein van 't Veer
        email                : rein@vantveer.me
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from typing import Optional, Any

from qgis.gui import QgisInterface

from .messaging.dependencies import report_missing_dependency


def classFactory(iface: QgisInterface) -> Optional[Any]:
    """
    Factory function for returning a Namari class instance from the Namari module: initializes the plugin.
    It will only return the full plugin if all the dependencies specified in the metadata.txt can be imported.

    :param iface: A QGIS interface instance.

    :return: The plugin instantiated against the QGIS interface
    """
    try:
        import sklearn
    except ImportError:
        report_missing_dependency('scikit-learn')

    # Do a local import: otherwise scikit-learn will give an import error before we can report installation instructions
    from .namari_plugin import Namari
    return Namari(iface)
