# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Namari
                                 A QGIS plugin
 This plugin allows you to detect anomalous features in spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-19
        copyright            : (C) 2021 by Rein van 't Veer
        email                : rein@vantveer.me
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import configparser
from importlib import import_module
from typing import Optional

from qgis.gui import QgisInterface

from .messaging.dependencies import report_missing_dependency
from .namari_plugin import Namari


def classFactory(iface: QgisInterface) -> Optional[Namari]:
    """
    Factory function for returning a Namari class instance from the Namari module: initializes the plugin.
    It will only return the full plugin if all the dependencies specified in the metadata.txt can be imported.

    :param iface: A QGIS interface instance.

    :return: The plugin instantiated against the QGIS interface
    """
    parser = configparser.ConfigParser()
    parser.optionxform = str
    parser.read('metadata.txt')

    general_metadata = dict(parser.items('general'))

    dependencies = general_metadata['plugin_dependencies'].split(',')
    dependencies = [d.strip() for d in dependencies]

    for package in dependencies:
        try:
            import_module(package)
        except ImportError:
            report_missing_dependency(package)
            return None

    return Namari(iface)
