name: Docker build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and checks by building the Docker image with build dependencies
        run: |
          docker build .
